module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/HhuLiSRKTzdCP4NjCXkt21',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/fptw1m.jpg',
    NEWSLETTER_JID: '120363406588763460@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'GAAJU-ᴍɪɴɪ',
    OWNER_NAME: 'ᴄʜʀɪs ɢᴀᴀᴊᴜ',
    OWNER_NUMBER: '2348069675806',
    BOT_VERSION: '1.0.2',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ ᴄʜʀɪs ɢᴀᴀᴊᴜ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBvGgyFsn0alyIDjw0z',
};
